[package]
name = "diesel-sample"
version = "0.1.0"
authors = ["Adri√°n Arroyo Calle <adrian.arroyocalle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "*", features = ["sqlite"] }
